import '../../../../core/services/entity_service.dart';

class ModelPurchaseOrderFields {
  static const String table = 'purchase_order';
  static const String tableViewWithForeignKeyLabels = 'view_purchase_orders';

  static const String poId = 'po_id';
  static const String poTotalAmount = 'po_total_amount';
  static const String poLineItemCount = 'po_line_item_count';
  static const String poRouteId = 'po_route_id';
  static const String poShopId = 'po_shop_id';
  static const String userComment = 'user_comment';
  static const String profitToShop = 'profit_to_shop';
  static const String poLat = 'po_lat';
  static const String poLong = 'po_long';
  static const String status = 'status';
  static const String createdBy = 'created_by';
  static const String updatedBy = 'updated_by';
  static const String createdAt = 'created_at';
  static const String visitOrder = 'visit_order';
  static const String updatedAt = 'updated_at';

  static const Map<String, String> labels = {
    poId: 'PO',
    poTotalAmount: 'Total Amount',
    poLineItemCount: 'Line Item Count',
    poRouteId: 'Route',
    poShopId: 'Shop',
    userComment: 'User Comment',
    profitToShop: 'Profit to Shop',
    poLat: 'Latitude',
    poLong: 'Longitude',
    status: 'Status',
    createdBy: 'Created By',
    updatedBy: 'Updated By',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    visitOrder: 'Visit Order',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelPurchaseOrder {
  final String? poId; // nullable, generated by DB
  final double? poTotalAmount; // nullable
  final int? poLineItemCount; // nullable
  final String? poRouteId; // required FK
  final String? poShopId; // required FK
  final String? userComment; // nullable
  final double? profitToShop; // nullable
  final double? poLat; // nullable
  final double? poLong; // nullable
  final String? status; // nullable, DB default
  final String? createdBy; // required FK
  final String? updatedBy; // required FK
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final int? visitOrder; // nullable, from view join
  final Map<String, dynamic> _resolvedLabels;

  ModelPurchaseOrder({
    this.poId,
    this.poTotalAmount,
    this.poLineItemCount,
    this.poRouteId,
    this.poShopId,
    this.userComment,
    this.profitToShop,
    this.poLat,
    this.poLong,
    this.status,
    this.createdBy,
    this.updatedBy,
    this.createdAt,
    this.updatedAt,
    this.visitOrder,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelPurchaseOrder.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelPurchaseOrder(
      poId: map[ModelPurchaseOrderFields.poId] as String?,
      poTotalAmount: map[ModelPurchaseOrderFields.poTotalAmount] != null
          ? double.tryParse(
              map[ModelPurchaseOrderFields.poTotalAmount].toString(),
            )
          : null,
      poLineItemCount: map[ModelPurchaseOrderFields.poLineItemCount] != null
          ? int.tryParse(
              map[ModelPurchaseOrderFields.poLineItemCount].toString(),
            )
          : null,
      poRouteId: map[ModelPurchaseOrderFields.poRouteId] as String?,
      poShopId: map[ModelPurchaseOrderFields.poShopId] as String?,
      userComment: map[ModelPurchaseOrderFields.userComment] as String?,
      profitToShop: map[ModelPurchaseOrderFields.profitToShop] != null
          ? double.tryParse(
              map[ModelPurchaseOrderFields.profitToShop].toString(),
            )
          : null,
      poLat: map[ModelPurchaseOrderFields.poLat] != null
          ? double.tryParse(map[ModelPurchaseOrderFields.poLat].toString())
          : null,
      poLong: map[ModelPurchaseOrderFields.poLong] != null
          ? double.tryParse(map[ModelPurchaseOrderFields.poLong].toString())
          : null,
      status: map[ModelPurchaseOrderFields.status] as String?,
      createdBy: map[ModelPurchaseOrderFields.createdBy] as String?,
      updatedBy: map[ModelPurchaseOrderFields.updatedBy] as String?,
      createdAt: map[ModelPurchaseOrderFields.createdAt] != null
          ? DateTime.tryParse(
              map[ModelPurchaseOrderFields.createdAt].toString(),
            )
          : null,
      updatedAt: map[ModelPurchaseOrderFields.updatedAt] != null
          ? DateTime.tryParse(
              map[ModelPurchaseOrderFields.updatedAt].toString(),
            )
          : null,
      visitOrder: map[ModelPurchaseOrderFields.visitOrder] != null
          ? int.tryParse(map[ModelPurchaseOrderFields.visitOrder].toString())
          : null,
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};

    if (poId != null) map[ModelPurchaseOrderFields.poId] = poId;
    if (poTotalAmount != null)
      map[ModelPurchaseOrderFields.poTotalAmount] = poTotalAmount;
    if (poLineItemCount != null)
      map[ModelPurchaseOrderFields.poLineItemCount] = poLineItemCount;
    if (poRouteId != null) map[ModelPurchaseOrderFields.poRouteId] = poRouteId;
    if (poShopId != null) map[ModelPurchaseOrderFields.poShopId] = poShopId;
    if (userComment != null)
      map[ModelPurchaseOrderFields.userComment] = userComment;
    if (profitToShop != null)
      map[ModelPurchaseOrderFields.profitToShop] = profitToShop;
    if (poLat != null) map[ModelPurchaseOrderFields.poLat] = poLat;
    if (poLong != null) map[ModelPurchaseOrderFields.poLong] = poLong;
    if (status != null) map[ModelPurchaseOrderFields.status] = status;
    if (createdBy != null) map[ModelPurchaseOrderFields.createdBy] = createdBy;
    if (updatedBy != null) map[ModelPurchaseOrderFields.updatedBy] = updatedBy;
    if (createdAt != null)
      map[ModelPurchaseOrderFields.createdAt] = createdAt!.toIso8601String();
    if (updatedAt != null)
      map[ModelPurchaseOrderFields.updatedAt] = updatedAt!.toIso8601String();
    if (visitOrder != null)
      map[ModelPurchaseOrderFields.visitOrder] = visitOrder;

    return map;
  }

  Map<String, dynamic> toJson() {
    return {
      'poId': poId,
      'poTotalAmount': poTotalAmount,
      'poLineItemCount': poLineItemCount,
      'poRouteId': poRouteId,
      'poShopId': poShopId,
      'userComment': userComment,
      'profitToShop': profitToShop,
      'poLat': poLat,
      'poLong': poLong,
      'status': status,
      'createdBy': createdBy,
      'updatedBy': updatedBy,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'visitOrder': visitOrder,
    };
  }

  factory ModelPurchaseOrder.fromJson(Map<String, dynamic> json) {
    return ModelPurchaseOrder(
      poId: json['poId'] as String,
      poTotalAmount: (json['poTotalAmount'] as num?)?.toDouble(),
      poLineItemCount: json['poLineItemCount'] as int?,
      poRouteId: json['poRouteId'] as String,
      poShopId: json['poShopId'] as String,
      userComment: json['userComment'] as String?,
      profitToShop: (json['profitToShop'] as num?)?.toDouble(),
      poLat: (json['poLat'] as num?)?.toDouble(),
      poLong: (json['poLong'] as num?)?.toDouble(),
      status: json['status'] as String? ?? 'confirmed',
      createdBy: json['createdBy'] as String,
      updatedBy: json['updatedBy'] as String,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }
}

class ModelPurchaseOrderMapper implements EntityMapper<ModelPurchaseOrder> {
  @override
  ModelPurchaseOrder fromMap(Map<String, dynamic> map) =>
      ModelPurchaseOrder.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelPurchaseOrder entity) => entity.toMap();
}
