import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const productEntityMeta = EntityMeta(
  entityName: 'Product',
  entityNameLower: 'product',
  entityNamePlural: 'Products',
  entityNamePluralLower: 'products',
);

class ModelProductFields {
  static const String table = 'product';
  static const String tableViewWithForeignKeyLabels = 'view_products';

  static const String productId = 'product_id';
  static const String productType = 'product_type';
  static const String productName = 'product_name';
  static const String productNameHindi = 'product_name_hindi';
  static const String productWeightValue = 'product_weight_value';
  static const String productWeightUnit = 'product_weight_unit';
  static const String purchaseRateForRetailer = 'purchase_rate_for_retailer';
  static const String mrp = 'mrp';
  static const String packagingType = 'packaging_type';
  static const String piecesPerOuter = 'pieces_per_outer';
  static const String isOuter = 'is_outer';
  static const String isActive = 'is_active';
  static const String isAvailable = 'is_available';
  static const String productImage = 'product_image_url';
  static const String createdBy = 'created_by';
  static const String updatedBy = 'updated_by';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String qtyInDecimal = 'qtyindecimal';

  static const Map<String, String> labels = {
    productId: 'Product',
    productType: 'Type',
    productName: 'Name',
    productNameHindi: 'Name (Hindi)',
    productWeightValue: 'Weight',
    productWeightUnit: 'Weight Unit',
    purchaseRateForRetailer: 'Retailer Rate',
    mrp: 'MRP',
    packagingType: 'Packaging',
    piecesPerOuter: 'Pieces per Outer',
    isOuter: 'Is Outer',
    isActive: 'Is Active',
    isAvailable: 'Is Available',
    qtyInDecimal: 'Qty in Decimal',
    productImage: 'Product Image',
    createdBy: 'Created By',
    updatedBy: 'Updated By',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelProduct {
  final String? productId; // nullable, generated by DB
  final String productType;
  final String productName;
  final String? productNameHindi;
  final double productWeightValue;
  final String productWeightUnit;
  final double purchaseRateForRetailer;
  final double mrp;
  final String packagingType;
  final int? piecesPerOuter;
  final bool isOuter;
  final bool isActive;
  final bool isAvailable;
  final bool qtyInDecimal; // new field
  final String? productImage;
  final String? createdBy; // uuid, may be nullable
  final String? updatedBy; // uuid, may be nullable
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default

  ModelProduct({
    this.productId,
    required this.productType,
    required this.productName,
    this.productNameHindi,
    required this.productWeightValue,
    required this.productWeightUnit,
    required this.purchaseRateForRetailer,
    required this.mrp,
    required this.packagingType,
    this.piecesPerOuter,
    required this.isOuter,
    required this.isActive,
    required this.isAvailable,
    required this.qtyInDecimal,
    this.productImage,
    this.createdBy,
    this.updatedBy,
    this.createdAt,
    this.updatedAt,
  });

  factory ModelProduct.fromMap(Map<String, dynamic> map) {
    return ModelProduct(
      productId: map[ModelProductFields.productId]?.toString(),
      productType: map[ModelProductFields.productType]?.toString() ?? '',
      productName: map[ModelProductFields.productName]?.toString() ?? '',
      productNameHindi: map[ModelProductFields.productNameHindi]?.toString(),
      productWeightValue:
          double.tryParse(
            map[ModelProductFields.productWeightValue]?.toString() ?? '',
          ) ??
          0.0,
      productWeightUnit:
          map[ModelProductFields.productWeightUnit]?.toString() ?? '',
      purchaseRateForRetailer:
          double.tryParse(
            map[ModelProductFields.purchaseRateForRetailer]?.toString() ?? '',
          ) ??
          0.0,
      mrp:
          double.tryParse(map[ModelProductFields.mrp]?.toString() ?? '') ?? 0.0,
      packagingType: map[ModelProductFields.packagingType]?.toString() ?? '',
      piecesPerOuter: int.tryParse(
        map[ModelProductFields.piecesPerOuter]?.toString() ?? '',
      ),
      isOuter: map[ModelProductFields.isOuter] == true,
      isActive: map[ModelProductFields.isActive] != false, // Default to true
      isAvailable:
          map[ModelProductFields.isAvailable] != false, // Default to true
      qtyInDecimal:
          map[ModelProductFields.qtyInDecimal] == true, // Default to false
      productImage: map[ModelProductFields.productImage]?.toString(),
      createdBy: map[ModelProductFields.createdBy]?.toString(),
      updatedBy: map[ModelProductFields.updatedBy]?.toString(),
      createdAt: map[ModelProductFields.createdAt] != null
          ? DateTime.tryParse(map[ModelProductFields.createdAt].toString())
          : null,
      updatedAt: map[ModelProductFields.updatedAt] != null
          ? DateTime.tryParse(map[ModelProductFields.updatedAt].toString())
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (productId != null) ModelProductFields.productId: productId,
      ModelProductFields.productType: productType,
      ModelProductFields.productName: productName,
      if (productNameHindi != null) ModelProductFields.productNameHindi: productNameHindi,
      ModelProductFields.productWeightValue: productWeightValue,
      ModelProductFields.productWeightUnit: productWeightUnit,
      ModelProductFields.purchaseRateForRetailer: purchaseRateForRetailer,
      ModelProductFields.mrp: mrp,
      ModelProductFields.packagingType: packagingType,
      if (piecesPerOuter != null)
        ModelProductFields.piecesPerOuter: piecesPerOuter,
      ModelProductFields.isOuter: isOuter,
      ModelProductFields.isActive: isActive,
      ModelProductFields.isAvailable: isAvailable,
      ModelProductFields.qtyInDecimal: qtyInDecimal,
      if (productImage != null) ModelProductFields.productImage: productImage,
      if (createdBy != null) ModelProductFields.createdBy: createdBy,
      if (updatedBy != null) ModelProductFields.updatedBy: updatedBy,
      if (createdAt != null)
        ModelProductFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelProductFields.updatedAt: updatedAt!.toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'productId': productId,
      'productType': productType,
      'productName': productName,
      'productNameHindi': productNameHindi,
      'productWeightValue': productWeightValue,
      'productWeightUnit': productWeightUnit,
      'purchaseRateForRetailer': purchaseRateForRetailer,
      'mrp': mrp,
      'packagingType': packagingType,
      'piecesPerOuter': piecesPerOuter,
      'isOuter': isOuter,
      'isActive': isActive,
      'isAvailable': isAvailable,
      'qtyInDecimal': qtyInDecimal,
      'productImage': productImage,
      'createdBy': createdBy,
      'updatedBy': updatedBy,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
    };
  }

  factory ModelProduct.fromJson(Map<String, dynamic> json) {
    return ModelProduct(
      productId: json['productId'] as String,
      productType: json['productType'] as String,
      productName: json['productName'] as String,
      productNameHindi: json['productNameHindi'] as String?,
      productWeightValue: (json['productWeightValue'] as num).toDouble(),
      productWeightUnit: json['productWeightUnit'] as String,
      purchaseRateForRetailer: (json['purchaseRateForRetailer'] as num)
          .toDouble(),
      mrp: (json['mrp'] as num).toDouble(),
      packagingType: json['packagingType'] as String,
      piecesPerOuter: json['piecesPerOuter'] as int?,
      isOuter: json['isOuter'] as bool? ?? false,
      isActive: json['isActive'] as bool? ?? true,
      isAvailable: json['isAvailable'] as bool? ?? true,
      qtyInDecimal: json['qtyInDecimal'] as bool? ?? false,
      productImage: json['productImage'] as String?,
      createdBy: json['createdBy'] as String,
      updatedBy: json['updatedBy'] as String,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
    );
  }
}

class ModelProductMapper implements EntityMapper<ModelProduct> {
  @override
  ModelProduct fromMap(Map<String, dynamic> map) => ModelProduct.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelProduct entity) => entity.toMap();
}
