import '../../../../core/services/entity_service.dart';

class ModelShopFields {
  static const String table = 'shops';
  static const String tableViewWithForeignKeyLabels = 'view_shops';

  static const String shopId = 'shop_id';
  static const String shopName = 'shop_name';
  static const String shopsPrimaryRoute = 'shops_primary_route';
  static const String shopNote = 'shop_note';
  static const String hiddenNote = 'hidden_note';
  static const String shopMobile1 = 'shop_mobile_1';
  static const String shopMobile2 = 'shop_mobile_2';
  static const String shopPersonName = 'shop_person_name';
  static const String isActive = 'is_active';
  static const String shopLocationUrl = 'shop_location_url';
  static const String shopLandmark = 'shop_landmark';
  static const String shopAddress = 'shop_address';
  static const String shopPhotoId = 'shop_photo_id';
  static const String shopPhotoUrl = 'shop_photo_url';
  static const String shopLat = 'shop_lat';
  static const String shopLong = 'shop_long';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String visitOrder = 'visit_order';

  static const Map<String, String> labels = {
    shopId: 'Shop',
    shopName: 'Shop Name',
    shopsPrimaryRoute: 'Primary Route',
    shopNote: 'Shop Note',
    hiddenNote: 'Hidden Note',
    shopMobile1: 'Mobile 1',
    shopMobile2: 'Mobile 2',
    shopPersonName: 'Contact Person',
    isActive: 'Is Active',
    shopLocationUrl: 'Location URL',
    shopLandmark: 'Landmark',
    shopAddress: 'Address',
    shopPhotoId: 'Photo ID',
    shopPhotoUrl: 'Photo URL',
    shopLat: 'Latitude',
    shopLong: 'Longitude',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    visitOrder: 'Visit Order',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelShop {
  final String? shopId; // nullable, generated by DB
  final String shopName; // required
  final String? shopsPrimaryRoute; // nullable FK
  final String? shopNote;
  final String? hiddenNote;
  final String? shopMobile1;
  final String? shopMobile2;
  final String? shopPersonName;
  final bool isActive; // default true
  final String? shopLocationUrl;
  final String? shopLandmark;
  final String? shopAddress;
  final String? shopPhotoId;
  final String? shopPhotoUrl;
  final double? shopLat;
  final double? shopLong;
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final int? visitOrder;
  final Map<String, dynamic> _resolvedLabels;

  ModelShop({
    this.shopId,
    required this.shopName,
    this.shopsPrimaryRoute,
    this.shopNote,
    this.hiddenNote,
    this.shopMobile1,
    this.shopMobile2,
    this.shopPersonName,
    this.isActive = true,
    this.shopLocationUrl,
    this.shopLandmark,
    this.shopAddress,
    this.shopPhotoId,
    this.shopPhotoUrl,
    this.shopLat,
    this.shopLong,
    this.createdAt,
    this.updatedAt,
    this.visitOrder,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelShop.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelShop(
      shopId: map[ModelShopFields.shopId],
      shopName: map[ModelShopFields.shopName],
      shopsPrimaryRoute: map[ModelShopFields.shopsPrimaryRoute],
      shopNote: map[ModelShopFields.shopNote],
      hiddenNote: map[ModelShopFields.hiddenNote],
      shopMobile1: map[ModelShopFields.shopMobile1],
      shopMobile2: map[ModelShopFields.shopMobile2],
      shopPersonName: map[ModelShopFields.shopPersonName],
      isActive: map[ModelShopFields.isActive] ?? true,
      shopLocationUrl: map[ModelShopFields.shopLocationUrl],
      shopLandmark: map[ModelShopFields.shopLandmark],
      shopAddress: map[ModelShopFields.shopAddress],
      shopPhotoId: map[ModelShopFields.shopPhotoId],
      shopPhotoUrl: map[ModelShopFields.shopPhotoUrl],
      shopLat: map[ModelShopFields.shopLat]?.toDouble(),
      shopLong: map[ModelShopFields.shopLong]?.toDouble(),
      createdAt: map[ModelShopFields.createdAt] != null
          ? DateTime.tryParse(map[ModelShopFields.createdAt])
          : null,
      updatedAt: map[ModelShopFields.updatedAt] != null
          ? DateTime.tryParse(map[ModelShopFields.updatedAt])
          : null,
      visitOrder: map[ModelShopFields.visitOrder] as int?,
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (shopId != null) ModelShopFields.shopId: shopId,
      ModelShopFields.shopName: shopName,
      if (shopsPrimaryRoute != null)
        ModelShopFields.shopsPrimaryRoute: shopsPrimaryRoute,
      if (shopNote != null) ModelShopFields.shopNote: shopNote,
      if (hiddenNote != null) ModelShopFields.hiddenNote: hiddenNote,
      if (shopMobile1 != null) ModelShopFields.shopMobile1: shopMobile1,
      if (shopMobile2 != null) ModelShopFields.shopMobile2: shopMobile2,
      if (shopPersonName != null)
        ModelShopFields.shopPersonName: shopPersonName,
      ModelShopFields.isActive: isActive,
      if (shopLocationUrl != null)
        ModelShopFields.shopLocationUrl: shopLocationUrl,
      if (shopLandmark != null) ModelShopFields.shopLandmark: shopLandmark,
      if (shopAddress != null) ModelShopFields.shopAddress: shopAddress,
      if (shopPhotoId != null) ModelShopFields.shopPhotoId: shopPhotoId,
      if (shopPhotoUrl != null) ModelShopFields.shopPhotoUrl: shopPhotoUrl,
      if (shopLat != null) ModelShopFields.shopLat: shopLat,
      if (shopLong != null) ModelShopFields.shopLong: shopLong,
      if (createdAt != null)
        ModelShopFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelShopFields.updatedAt: updatedAt!.toIso8601String(),
      if (visitOrder != null) ModelShopFields.visitOrder: visitOrder,
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'shopId': shopId,
      'shopName': shopName,
      'shopsPrimaryRoute': shopsPrimaryRoute,
      'shopNote': shopNote,
      'hiddenNote': hiddenNote,
      'shopMobile1': shopMobile1,
      'shopMobile2': shopMobile2,
      'shopPersonName': shopPersonName,
      'isActive': isActive,
      'shopLocationUrl': shopLocationUrl,
      'shopLandmark': shopLandmark,
      'shopAddress': shopAddress,
      'shopPhotoId': shopPhotoId,
      'shopPhotoUrl': shopPhotoUrl,
      'shopLat': shopLat,
      'shopLong': shopLong,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'visitOrder': visitOrder,
    };
  }

  factory ModelShop.fromJson(Map<String, dynamic> json) {
    return ModelShop(
      shopId: json['shopId'] as String,
      shopName: json['shopName'] as String,
      shopsPrimaryRoute: json['shopsPrimaryRoute'] as String?,
      shopNote: json['shopNote'] as String?,
      hiddenNote: json['hiddenNote'] as String?,
      shopMobile1: json['shopMobile1'] as String?,
      shopMobile2: json['shopMobile2'] as String?,
      shopPersonName: json['shopPersonName'] as String?,
      isActive: json['isActive'] as bool? ?? true,
      shopLocationUrl: json['shopLocationUrl'] as String?,
      shopLandmark: json['shopLandmark'] as String?,
      shopAddress: json['shopAddress'] as String?,
      shopPhotoId: json['shopPhotoId'] as String?,
      shopPhotoUrl: json['shopPhotoUrl'] as String?,
      shopLat: (json['shopLat'] as num?)?.toDouble(),
      shopLong: (json['shopLong'] as num?)?.toDouble(),
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }
}

class ModelShopMapper implements EntityMapper<ModelShop> {
  @override
  ModelShop fromMap(Map<String, dynamic> map) => ModelShop.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelShop entity) => entity.toMap();
}
